% Run this first on the whole folder to produce Matlab save files with
% less data stored in them (much faster to load later).
% (C) 2023/09/17 by Benjamin Seibold

removed_fields = {
    'trajectory_id',...
    'y_position_corrected_meters',...
    'length',...
    'width',...
    'height',...
    'total_distance_traversed_meters',...
    'acceleration_meters_per_second_per_second',...
    'road_grade_radians',...
    'reference_a1_meters_per_second_per_second',...
    'reference_a2_meters_per_second_per_second',...
    'total_fuel_consumed_grams',...
    'total_fuel_consumed_gallons',...
    'total_fuel_economy_mpg'
    'total_fuel_consumed_flat_road_grams',...
    'total_fuel_consumed_flat_road_gallons',...
    'total_fuel_economy_flat_road_mpg',...
    'reference_fuel_rate_grams_per_second',...
    'percent_reference_infeasibility',...
    'total_reference_fuel_consumed_grams',...
    'reference_fuel_rate_flat_road_grams_per_second',...
    'percent_reference_infeasibility_flat_road',...
    'total_reference_fuel_consumed_flat_road_grams',...
    'downstream_av_id',...
    'distance_to_downstream_av_meters',...
    'downstream_engaged_av_id',...
    'distance_to_downstream_engaged_av_meters'};

data_files = dir('I-24MOTION_????-??-??_??-??-??.json');
for j = 1:length(data_files)
    % Load data file
    filename = data_files(j).name;
    fprintf('Loading %s ...',filename), tic
    fid = fopen(filename);
    data = fread(fid,inf);
    fclose(fid);
    fprintf(' Done (%0.0fsec).\n',toc)
    fprintf('Decoding data structures ...'), tic
    data = jsondecode(char(data'));
    fprintf(' Done (%0.0fsec).\n',toc)
    % Reduce data
    fprintf('Remove fields ...'), tic
    data = rmfield(data,removed_fields);
    fprintf(' Done (%0.0fsec).\n',toc)
    % Save new data file
    filename = [filename(1:end-5),'_reduced.mat'];
    fprintf('Save as %s ...',filename), tic
    save(filename,'data')
    fprintf(' Done (%0.0fsec).\n',toc)
end
