function version = dataVersion()
% MVT.DATAVERSION  Version of the released MVT data set this code produces.
%
% Purpose
%   One place to state which version of the derived data the pipeline emits, so
%   the number cannot drift between scripts, logs, and documentation. This is
%   the version of *our* derived products (slim/full/gps), not of the upstream
%   I-24 MOTION data, which is versioned independently by the observatory and
%   is unchanged by anything here.
%
% Outputs
%   version  char, e.g. '2.2'
%
% History
%   2.1  The data set used for the Nature submission.
%   2.2  Deterministic fuel quadrature (mvt.neumaierDot in place of `dot`).
%        Same inputs, same models; the fuel totals are no longer dependent on
%        which BLAS the host platform ships, so the pipeline now returns
%        identical bytes on Mac and PC. Numerically inert at reported
%        precision - two full segments regenerated byte-for-byte identically.
%        See docs/REPRODUCIBLE_QUADRATURE.md.
%
% Notes
%   Bump the minor version whenever a change alters, or could alter, the bytes
%   of the released data - even when no value changes at reported precision.
%   The point of the version is to let someone holding two copies of the data
%   tell whether they should be identical.
%
% (C) 2026 CIRCLES Consortium. BSD-3-Clause.

version = '2.2';
end
