function [] = probe_jsonencode(outputFile)
% PROBE_JSONENCODE  Record how this MATLAB release formats numbers in JSON.
%
% Purpose
%   The Python port must write JSON that is byte-identical to MATLAB's
%   jsonencode. Most of the formatting rules were established from the released
%   data set, but that data only contains values in two magnitude bands
%   (<= 2.7e5 and ~1.67e9) and never contains Inf, so a few rules could only be
%   inferred. This script probes them directly. Run it once and hand the output
%   to python/tests/test_matjson_probe.py, which asserts that mvtpy agrees.
%
% Inputs
%   outputFile  (optional) where to write the probe results; default
%               python/matlab_probes/jsonencode_probe_<release>.json
%
% Outputs
%   A JSON file mapping a description of each probe value to the exact text
%   jsonencode produced for it.
%
% Usage
%   cd MVT_structured_data/Scripts
%   probe_jsonencode
%
% (C) 2026 CIRCLES Consortium. BSD-3-Clause.

if nargin < 1 || isempty(outputFile)
    here = fileparts(mfilename('fullpath'));
    outputFile = fullfile(here, ['jsonencode_probe_' version('-release') '.json']);
end

probes = { ...
    % --- magnitude band where the released data is silent (1e5 .. 1e9) ------
    'e5_integral',        1e5; ...
    'e5_fraction',        123456.789; ...
    'e6_integral',        1e6; ...
    'e6_fraction',        1234567.8912; ...
    'e7_fraction',        12345678.9123; ...
    'e8_fraction',        123456789.1234; ...
    'e9_boundary_below',  999999999.9999; ...
    'e9_boundary_at',     1e9; ...
    'e9_fraction',        1668599999.9836; ...
    'e15',                1e15; ...
    'e16',                1e16; ...
    % --- small magnitudes (data stops at 1e-4 because of 4-decimal rounding)-
    'em4',                0.0001; ...
    'em5',                0.00001; ...
    'em6',                0.000001; ...
    'em7_fraction',       1.2345e-07; ...
    % --- digit-count ladder: 15 digits round-trip vs 17 needed --------------
    'digits15',           1668599999.9836; ...
    'digits17',           1668691841.800001; ...
    'digits_short',       1.5; ...
    % --- signs, zeros, specials --------------------------------------------
    'zero',               0; ...
    'negative_zero',      -0; ...
    'negative_fraction', -3.25; ...
    'nan',                NaN; ...
    'inf',                Inf; ...
    'neg_inf',            -Inf; ...
    % --- integer-valued doubles and integer types ---------------------------
    'integral_small',     840; ...
    'integral_negative', -1; ...
    'int32_value',        int32(7); ...
    'logical_true',       true; ...
    'logical_false',      false};

results = struct();
for iProbe = 1:size(probes, 1)
    name = probes{iProbe, 1};
    value = probes{iProbe, 2};
    results.(name) = jsonencode(value);
    fprintf('%-20s %s\n', name, results.(name));
end

% Structural probes: field order, empty arrays, one-element arrays, strings.
results.struct_field_order = jsonencode(struct('b', 1, 'a', 2));
results.empty_numeric      = jsonencode(struct('x', []));
results.one_element_array  = jsonencode(struct('x', 5));
results.two_element_array  = jsonencode(struct('x', [5 6]));
results.string_escapes     = jsonencode(struct('s', sprintf('a"b\\c/d\te')));
results.nested_struct      = jsonencode(struct('a', struct('b', 1)));
results.struct_array       = jsonencode(struct('a', {1, 2}));
results.release            = version('-release');

fid = fopen(outputFile, 'w');
if fid < 0
    error('probe_jsonencode:cannotWrite', 'Could not write %s', outputFile);
end
cleanup = onCleanup(@() fclose(fid)); %#ok<NASGU>
fwrite(fid, jsonencode(results), 'char');
fprintf('\nWrote %s\n', outputFile);
end
